In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
cond = arr > 5 
cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
biggers = arr[arr>5] # Aplying conditions like a filter
biggers

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
smallers = biggers[biggers<9]
smallers

array([6, 7, 8], dtype=int8)

In [15]:
new_arr = smallers.copy() #using copy
new_arr

array([6, 7, 8], dtype=int8)

In [19]:
moded = new_arr*2
moded

array([12, 14, 16], dtype=int8)

arr #original

In [21]:
matriz = np.random.rand(3,4)
matriz

array([[0.68642146, 0.20408415, 0.04021389, 0.73049411],
       [0.47885051, 0.6508698 , 0.49681624, 0.36611139],
       [0.22692266, 0.99073701, 0.24093993, 0.68761827]])

In [22]:
matriz[matriz<0.5] = 0
matriz

array([[0.68642146, 0.        , 0.        , 0.73049411],
       [0.        , 0.6508698 , 0.        , 0.        ],
       [0.        , 0.99073701, 0.        , 0.68761827]])