# Funciones de Numpy

## Apuntes

.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.

arr = np.arange(0, 11)
arr ----> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr[0:6] ----> array([0, 1, 2, 3, 4, 5])
trozo_de_arr = arr[0:6]
trozo_de_arr[:] = 0
trozo_de_arr ----> array([0, 0, 0, 0, 0, 0])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.

arr ----> array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy ----> array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])
arr ----> array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Copy

In [7]:
import numpy as np

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
piece = arr[0:6]
piece

array([0, 1, 2, 3, 4, 5])

In [11]:
piece[:] = 0
piece

array([0, 0, 0, 0, 0, 0])

In [12]:
arr     ## DAMAGED ARRAY!, THATS WHY WE USE FUNCTION COPY

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [27]:
for i in range(0,6): #Fixing the arr
    arr[i] = i
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy()   # COPY THE ARR FATHER TO A NEW VARIABLE IMAGE OF HIM
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr_copy[:] = 100 # Changing the arr_copy values
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr #arr original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### También es posible copiar el array original y hacer el slicing en la misma linea

In [33]:
a = [1,2,3,4,5,6,7,8,9,10]
b = a.copy()[:6]
b

[1, 2, 3, 4, 5, 6]