## creating arrays

In [3]:
import numpy as np

In [6]:
list(range(0,10)) ## this is a python list 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10) ## And this is the way to do a numpy array.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(10) # making an array of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((10,5)) # making a matrix array of zeros, this can be useful as a preliminary outline

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((10,5)) # thes same than before but whit ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(10,10,10) ## generatin an array of numbers from a numeric defined range and the quantity of them, whit linspace function

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [16]:
np.eye(4) ## for the "lineal algebra" lovers, whit np eye function, we can make a matrix whit the main diagonal value in 1 and the others in zeros.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand() ## generating random float numbers between 0 and 1, whit the random rand function

0.7544856578374471

In [23]:
np.random.rand(5,5) ## matrix of random float numbers

array([[0.57701169, 0.9215408 , 0.98672252, 0.18638256, 0.3021187 ],
       [0.00685735, 0.47033149, 0.92853209, 0.21263552, 0.95613071],
       [0.13344467, 0.50086188, 0.96111575, 0.58866307, 0.20567636],
       [0.55633564, 0.33730867, 0.62787283, 0.9626005 , 0.74061461],
       [0.77090913, 0.18380534, 0.54948175, 0.55793573, 0.87005487]])

In [28]:
np.random.randint(1,15) ## random integer numbers generated whit the function random randint

2

In [29]:
np.random.randint(1,100,(10,10)) ## making an array of random integer numbers

array([[33, 55, 88, 20, 92, 29, 60, 59, 40, 82],
       [44,  1, 72, 37,  6,  5, 25, 55, 79, 70],
       [89, 59, 57, 86, 66, 84, 48, 17, 77, 55],
       [13, 81, 83, 58, 76, 42, 29, 95, 60, 83],
       [85, 57,  2, 96, 72, 39, 68, 64, 53, 38],
       [ 7, 73, 65, 96, 60, 18, 91, 58, 23, 15],
       [90, 54, 20, 49, 99, 21, 98, 18, 94, 52],
       [13, 38, 49, 41,  5, 50, 64, 33, 75, 27],
       [37, 31, 56, 84, 66, 74, 36,  5, 13, 42],
       [88, 91, 66, 83, 24, 46,  3, 63, 96, 29]])