# DIMENTIONS 

#### SCALAR

In [1]:
import numpy as np

In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#### VECTOR

In [3]:
vector = [1,2,3]
vector = np.array(vector)
print(vector)
vector.ndim

[1 2 3]


1

#### MATRIZ

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
matriz = np.array(matriz)
print(matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2

#### TENSOR 3D

In [5]:
tensor = [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
tensor = np.array(tensor)
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


3

#### TENSOR 4D

In [6]:
tensor = [[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]]
tensor = np.array(tensor)
print(tensor)
tensor.ndim

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]

  [[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]


4

#### CREATING ARRAY ADDING DIMENTIONS WHIT NUMPY

In [7]:
nueva = [1,2,3]
multi = np.array(nueva, ndmin=10)
print(multi)
multi.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

#### ADDING DIMENTIONS TO THE ARRAY 

In [8]:
lista = [4,5,6]
arr = np.array(lista)
expand = np.expand_dims(arr, axis=0)
print(expand)
expand.ndim

[[4 5 6]]


2

#### REMOVING DIMENTIONS FROM THE ARRAY

In [9]:
print(multi, multi.ndim)
multi_2 = np.squeeze(vector)
print(multi_2, multi_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
