In [5]:
import numpy as np
import pandas as pd

In [6]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]

### ponemos la lista creada dentro de un numpy array y la guardamos en una variabl

In [7]:
arr = np.array(lista)
print(arr)

[1 2 3 4 5 6 7 8 9]


### Chequeamos que la lista sea de tipo numpy array

In [8]:
type(arr)

numpy.ndarray

### generamos una matriz

In [11]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz= np.array(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0] + arr[5]

7

In [18]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### URGANDO EN LA MATRIZ

In [23]:
matriz[0, 2] #BUSCANDO POR INDICE EL VALOR ESPECIFICO DE ESE INDICE. [FILA, COLUMNA]

3

In [26]:
matriz[1:] # BUSCA POR FILAS, SE INDICA LA FILA DE PARTIDA [FILA: ...]

array([[4, 5, 6],
       [7, 8, 9]])

In [29]:
matriz[1:, 0:2] # BUSCA A PARTIR PRIMERO DE FILAS LUEGO "COMA" BUSCA EN COLUMNAS [FILA: ..., COLUMNA: ...]

array([[4, 5],
       [7, 8]])

###  MATRIZ 3D

In [32]:
matriz_3D = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]]
matriz_3D = np.array(matriz_3D)
matriz_3D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### The Middle

In [50]:
matriz_3D[2:4,1:2]

array([[ 8],
       [11]])