## NumPy Types

In [9]:
import numpy as np

In [28]:
data = [1,2,3,4,5,6]
arr = np.array(data)
arr

array([1, 2, 3, 4, 5, 6])

#### Value type of array

In [29]:
arr.dtype

dtype('int64')

#### Changing integer array to float array type

In [13]:
arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5., 6.])

#### Init an array whit Float type values

In [30]:
arr = np.array(data, dtype='float64')
arr.dtype

dtype('float64')

In [31]:
arr

array([1., 2., 3., 4., 5., 6.])

#### changing array type to boolean

In [32]:
arr2 = arr.astype(np.bool_)
arr2

array([ True,  True,  True,  True,  True,  True])

#### Changing array type to string

In [33]:
arr.astype(np.string_)

array([b'1.0', b'2.0', b'3.0', b'4.0', b'5.0', b'6.0'], dtype='|S32')

#### Changing array type to integer

In [35]:
arr3 = arr.astype(np.int8)
arr3

array([1, 2, 3, 4, 5, 6], dtype=int8)