In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2 # in python the list duplicate the data when he's multplied by two, but whit numpy arrays the operands do the work.

[1, 2, 1, 2]

In [4]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr2 = arr.copy()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### And that is like numpy operators works whit the arrays 

In [6]:
arr3 = arr2 * 2      # see the result
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr4 = arr + arr2 + arr3    # sumando 3 arrays
arr4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [8]:
arr5 = arr4 / arr
arr5

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [9]:
type(arr5[0]) # Type of data in the index 0

numpy.float64

In [10]:
matrix = np.reshape(arr, [2,5])
matrix2 = matrix.copy()
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
matrix2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [12]:
matrix3 = matrix + matrix2
matrix3

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [13]:
matrix*matrix2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [14]:
np.matmul(matrix,matrix2.T)

array([[ 55, 130],
       [130, 330]])

In [15]:
matrix @ matrix2.T

array([[ 55, 130],
       [130, 330]])