## shape and re-shape

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))
arr.shape         ## "Shape" show us the order of the structure, dimentions in quantity or columns and rows in the array.

(3, 2)

In [3]:
arr

array([[2, 7],
       [8, 3],
       [5, 7]])

In [4]:
arr.reshape(1,6)  ## we can change the order of the array structure.

array([[2, 7, 8, 3, 5, 7]])

In [5]:
np.reshape(arr,(2,3))    ## Another way to reshape

array([[2, 7, 8],
       [3, 5, 7]])

#### reshape in lenguages C, Fortrand and Computer System

In [6]:
np.reshape(arr,(2,3),'C') ## in lenguage C the reshaping order follow the rows

array([[2, 7, 8],
       [3, 5, 7]])

In [7]:
np.reshape(arr,(2,3),'F') ## in lenguage Fortrand the reshaping order follow the columns

array([[2, 5, 3],
       [8, 7, 7]])

In [8]:
np.reshape(arr,(2,3),'A') ## in the own system the reshaping order follow the rows

array([[2, 7, 8],
       [3, 5, 7]])

## Challenge

In [9]:
arr = np.random.randint(1,10,(4,4))
arr

array([[4, 1, 6, 5],
       [6, 7, 8, 1],
       [3, 3, 3, 1],
       [7, 9, 3, 2]])

In [10]:
arr.reshape(1,16)

array([[4, 1, 6, 5, 6, 7, 8, 1, 3, 3, 3, 1, 7, 9, 3, 2]])

In [11]:
arr.reshape(1,15)

ValueError: cannot reshape array of size 16 into shape (1,15)

In [ ]:
arr.reshape(2,8)

array([[3, 5, 8, 6, 9, 9, 8, 6],
       [8, 7, 6, 5, 4, 6, 3, 7]])

In [ ]:
arr.reshape(8,2)

array([[3, 5],
       [8, 6],
       [9, 9],
       [8, 6],
       [8, 7],
       [6, 5],
       [4, 6],
       [3, 7]])